export const movies = [
    {
      id: 1,
      title: 'Darkness Lisa',
      slug: 'darkness-lisa',
      genres: 'Adventure, Film-Noir, Thriller',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-11-600x885.jpg',
      rating: 8.5,
      duration: '2h 15min',
      releaseDate: '2023-03-15',
      status: 'released',
      description: 'In the shadows of a noir-inspired cityscape, Lisa embarks on a perilous adventure that challenges everything she thought she knew. A gripping thriller that keeps you on the edge of your seat from start to finish.',
      comments: 127
    },
    {
      id: 2,
      title: 'Star of Stage',
      slug: 'star-of-stage',
      genres: 'Biography, Music, Musical',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-10-600x885.jpg',
      rating: 9.2,
      duration: '2h 45min',
      releaseDate: '2024-01-20',
      status: 'released',
      description: 'The inspiring true story of a musical prodigy who rose from obscurity to become one of the greatest performers of our generation. A celebration of talent, perseverance, and the power of dreams.',
      comments: 243
    },
    {
      id: 3,
      title: "Michael's Life",
      slug: 'michaels-life',
      genres: 'Adventure, Family, Mystery',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-9-600x885.jpg',
      rating: 7.8,
      duration: '1h 58min',
      releaseDate: '2023-07-12',
      status: 'released',
      description: 'Join Michael on an unforgettable journey as he uncovers long-buried family secrets in this heartwarming adventure. A mystery that spans generations and brings a family closer together.',
      comments: 89
    },
    {
      id: 4,
      title: 'The Pursuit of Dreams',
      slug: 'the-pursuit-of-dreams',
      genres: 'Family, Fantasy, Musical',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-8-370x545.jpg',
      rating: 8.9,
      duration: '2h 10min',
      releaseDate: '2024-05-08',
      status: 'released',
      description: 'A magical musical adventure where dreams come alive and anything is possible. Follow a young dreamer as they discover that the greatest adventure is believing in yourself.',
      comments: 156
    },
    {
      id: 5,
      title: 'Historical Drama',
      slug: 'historical-drama',
      genres: 'Drama, History, Romance',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-2-370x545.jpg',
      rating: 8.3,
      duration: '2h 35min',
      releaseDate: '2023-11-22',
      status: 'released',
      description: 'Set against the backdrop of a tumultuous historical period, this epic romance tells the story of forbidden love and unwavering courage in the face of adversity.',
      comments: 198
    },
    {
      id: 6,
      title: 'Mystery Night',
      slug: 'mystery-night',
      genres: 'Crime, Mystery, Thriller',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-7-370x545.jpg',
      rating: 8.7,
      duration: '2h 05min',
      releaseDate: '2024-02-14',
      status: 'released',
      description: 'When darkness falls, secrets emerge. A detective races against time to solve a series of mysterious crimes before the killer strikes again in this pulse-pounding thriller.',
      comments: 214
    },
    {
      id: 7,
      title: 'Elegant Evening',
      slug: 'elegant-evening',
      genres: 'Drama, Romance',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-6-370x545.jpg',
      rating: 7.5,
      duration: '1h 52min',
      releaseDate: '2023-09-30',
      status: 'released',
      description: 'A sophisticated tale of love and longing set in the glamorous world of high society. An elegant exploration of romance, class, and the choices that define us.',
      comments: 76
    },
    {
      id: 8,
      title: 'Dark Knight',
      slug: 'dark-knight',
      genres: 'Action, Adventure, Fantasy',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-5-370x545.jpg',
      rating: 9.5,
      duration: '2h 32min',
      releaseDate: '2023-06-15',
      status: 'released',
      description: 'When evil threatens to consume the realm, a legendary warrior emerges from the shadows. An epic fantasy adventure filled with spectacular action and breathtaking visuals.',
      comments: 342
    },
    {
      id: 9,
      title: 'Space Adventure',
      slug: 'space-adventure',
      genres: 'Action, Sci-Fi, Thriller',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-4-370x545.jpg',
      rating: 8.1,
      duration: '2h 20min',
      releaseDate: '2024-08-22',
      status: 'released',
      description: 'Journey to the far reaches of the galaxy in this thrilling sci-fi adventure. When humanity faces its greatest threat, a crew of unlikely heroes must save the universe.',
      comments: 187
    },
    {
      id: 10,
      title: 'Love Story',
      slug: 'love-story',
      genres: 'Drama, Romance',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/02/title-poster-3-370x545.jpg',
      rating: 7.9,
      duration: '1h 48min',
      releaseDate: '2024-04-10',
      status: 'released',
      description: 'A timeless tale of love that transcends all boundaries. Two hearts, one unforgettable story that will make you believe in the power of true love.',
      comments: 165
    },
    {
      id: 11,
      title: 'Action Hero',
      slug: 'action-hero',
      genres: 'Action, Adventure',
      image: 'https://demo.gloriathemes.com/noxe/demo/wp-content/uploads/2020/01/title-poster-1-370x545.jpg',
      rating: 8.4,
      duration: '2h 08min',
      releaseDate: '2025-12-15',
      status: 'upcoming',
      description: 'Get ready for non-stop action as the ultimate hero returns for his most dangerous mission yet. Explosive stunts, thrilling combat, and an unstoppable hero.',
      comments: 45
    }
  ]